name: Build Mattermost Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y make

    - name: Build plugin
      run: make dist

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: plugin
        path: dist/*.tar.gz
